version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      time: "06:00"
      timezone: "Asia/Kolkata"
    groups:
      gh-actions:
        patterns: ["*"]
    assignees: [Jarmos-san]
